services:
  selenium-hub3:
    image: selenium/hub:latest
    container_name: selenium-hub3
    ports:
      - "4441:4441"
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub3
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub3
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
  chrome1:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub3
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub3
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443      
