services:
  selenium-hub5:
    image: selenium/hub:latest
    container_name: selenium-hub5
    ports:
      - "4451:4451"
      - "4452:4452"
      - "4453:4453"
      - "4455:4455"

  chrome5:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub5
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub5
      - SE_EVENT_BUS_PUBLISH_PORT=4452
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4453
   
